# Generated by Django 5.0.2 on 2024-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_Auth', '0002_rename_is_customer_user_is_admin_user_is_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(null=True, upload_to='Staffs'),
        ),
        migrations.AddField(
            model_name='user',
            name='Mobile',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Place',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
