# Generated by Django 4.2.4 on 2024-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=25)),
                ('Place', models.CharField(max_length=50)),
                ('Refered_By', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
