# Generated by Django 4.2.4 on 2024-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='Status',
            field=models.CharField(default='PENDING', max_length=25),
        ),
    ]
