# Generated by Django 4.2.4 on 2024-03-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0002_leads_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='Refered_By',
        ),
    ]
