# Generated by Django 4.2.4 on 2024-03-28 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Leads', '0003_remove_leads_refered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='Staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
