# Generated by Django 4.2.4 on 2024-03-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0005_lead_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_timeline',
            name='Color',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
