# Generated by Django 4.2.4 on 2024-03-28 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0006_alter_lead_timeline_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_timeline',
            name='Lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Leads.leads'),
            preserve_default=False,
        ),
    ]
