# Generated by Django 5.0.2 on 2024-02-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Name',
            field=models.CharField(default='Place', max_length=100),
            preserve_default=False,
        ),
    ]
