# Generated by Django 4.2.4 on 2024-02-27 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Added_Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
