# Generated by Django 4.2.4 on 2024-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_place_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=1)),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Place', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
