# Generated by Django 4.2.4 on 2024-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_agents_place_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=1)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
