# Generated by Django 4.2.4 on 2024-02-28 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_collage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Place', models.CharField(max_length=50)),
                ('Collage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Core.collage')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Core.course')),
            ],
        ),
    ]
