# Generated by Django 4.2.4 on 2024-02-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='Rank',
            field=models.CharField(choices=[('MAIN', 'MAIN'), ('SUB', 'SUB')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
