# Generated by Django 4.2.4 on 2024-02-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_agents_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='Rank',
            field=models.CharField(choices=[('Main', 'Main'), ('Sub', 'Sub')], max_length=50),
        ),
    ]
