# Generated by Django 4.2.4 on 2024-02-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_agents_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='Place',
        ),
    ]
