# Generated by Django 4.2.4 on 2024-02-29 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_remove_agents_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.course')),
            ],
        ),
    ]
