# Generated by Django 4.2.4 on 2024-02-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_course_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Addon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.course_addon'),
        ),
        migrations.AddField(
            model_name='student',
            name='Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.agents'),
        ),
        migrations.AddField(
            model_name='student',
            name='Collage_Payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='Discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='Donation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='Fees',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='First_Payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='Service',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='Total',
            field=models.FloatField(default=0.0),
        ),
    ]
