# Generated by Django 4.2.4 on 2024-03-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_student_addon_student_agent_student_collage_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Agent',
        ),
        migrations.AddField(
            model_name='student',
            name='Main_Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_agent', to='Core.agents'),
        ),
        migrations.AddField(
            model_name='student',
            name='Sub_Agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_agent', to='Core.agents'),
        ),
    ]
