# Generated by Django 4.2.4 on 2024-03-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_remove_student_agent_student_main_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Agent_Commission',
            field=models.FloatField(default=0.0),
        ),
    ]
