# Generated by Django 4.2.4 on 2024-03-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_remove_collage_agent_remove_collage_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
