# Generated by Django 4.2.4 on 2024-03-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_place_image_place_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Type',
            new_name='Location',
        ),
    ]
