# Generated by Django 4.2.4 on 2024-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_rename_type_place_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=100)),
                ('Sub_Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(null=True, upload_to='News')),
                ('Description', models.TextField()),
            ],
        ),
    ]
