# Generated by Django 4.2.4 on 2024-03-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Degree',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=50),
            preserve_default=False,
        ),
    ]
