# Generated by Django 4.2.4 on 2024-03-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_course_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Department',
            field=models.CharField(choices=[('Art', 'Art'), ('Medical', 'Medical'), ('Nusring', 'Nusring'), ('Pharmacy', 'Pharmacy'), ('Engineering', 'Engineering'), ('Physiotherapy', 'Physiotherapy')], default='Art', max_length=50),
        ),
    ]
