# Generated by Django 4.2.4 on 2024-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Department',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Medical', 'Medical'), ('Nusring', 'Nusring'), ('Pharmacy', 'Pharmacy'), ('Engineering', 'Engineering'), ('Physiotherapy', 'Physiotherapy')], default='Arts', max_length=50),
        ),
    ]
