# Generated by Django 4.2.4 on 2024-03-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Degree',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG'), ('Diploma', 'Diploma')], max_length=50),
        ),
    ]
