# Generated by Django 4.2.4 on 2024-03-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_alter_course_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Department',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Medical', 'Medical'), ('Nursing', 'Nursing'), ('Pharmacy', 'Pharmacy'), ('Engineering', 'Engineering'), ('Physiotherapy', 'Physiotherapy')], default='Arts', max_length=50),
        ),
    ]
