# Generated by Django 4.2.4 on 2024-02-29 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0013_student_addon_student_agent_student_collage_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Amount', models.FloatField(default=0.0)),
                ('Agents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.agents')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.entry_categories')),
                ('Collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.collage')),
                ('Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.student')),
            ],
        ),
    ]
