# Generated by Django 4.2.4 on 2024-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_categories',
            name='CATID',
        ),
        migrations.AddField(
            model_name='entry_categories',
            name='FOT',
            field=models.CharField(default='Elevate', max_length=10),
        ),
    ]
